server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://47.108.151.199:3306/jpkc
      username: root
      password: lb82ndLF
      max-active: 10
      login-timeout: 60000

