server:
  port: 80

# spring配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://47.108.151.199:23306/jpkc
      username: root
      password: lb82ndLF
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,slf4j


# mybatis-plus 文件路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

# swagger
swagger:
  base-package: com.study.jpkc.controller
  version: 1.0.0
  tittle: 精品课程网站
  description: 精品课程网站 API 接口文档
  terms-of-service-url: http://www.baidu.com
  license: jpck
  license-url: http://www.baidu.com